const sources = [
  {id:'science_for_africa',name:'Science for Africa Foundation',region:'Africa',state:'structured_beta_detail',priority:'critical',access:'direct',url:'https://scienceforafrica.foundation/funding',note:'African-led funding and Grand Challenges Africa. Detail pages are structured beta; index state alone is not treated as proof a call is open.',focus:'Africa-led science, health, climate, innovation and capacity strengthening.',use:'Best for African institutions, African-led teams and partners seeking continent-focused calls. Always confirm the specific country route and stage.'},
  {id:'idrc',name:'International Development Research Centre',region:'global_majority',state:'structured_beta',priority:'high',access:'direct',url:'https://idrc-crdi.ca/en/funding',note:'Research funding focused on development priorities, with source-specific parsing for call fields and explicit budget ambiguity handling.',focus:'Development research, policy, innovation and equitable partnerships.',use:'Useful for Global Majority research teams and consortia. Award amounts are shown only when the source text is semantically unambiguous.'},
  {id:'tdr_who',name:'WHO/TDR',region:'global_majority',state:'index_only',priority:'critical',access:'direct',url:'https://tdr.who.int/grants',note:'Global health research and training. Open calls route through the eTDR portal and are therefore link-only until a structured portal adapter is available.',focus:'Diseases of poverty, implementation research, training and institutional capacity.',use:'Use this as a verified gateway to TDR opportunities; open-call status must be confirmed in eTDR.'},
  {id:'cepi',name:'CEPI',region:'global',state:'partial',priority:'high',access:'mixed',url:'https://cepi.net/calls-for-proposals',note:'Vaccine and epidemic-preparedness funding. Call index is authoritative; some specifications are PDF-backed and remain gated.',focus:'Vaccines, epidemic preparedness, platform technologies and outbreak readiness.',use:'Check the primary call and attached specifications carefully; important requirements may sit in authoritative PDFs.'},
  {id:'elrha',name:'Elrha',region:'global',state:'index_only',priority:'high',access:'direct',url:'https://www.elrha.org/funding-opportunities/',note:'Humanitarian research and innovation. Current listings can include procurement/consultancy notices, so call type must be verified.',focus:'Humanitarian health, innovation and evidence in crisis settings.',use:'Confirm whether a listing is a research grant, innovation call, procurement notice or consultancy before investing effort.'},
  {id:'grand_challenges_canada',name:'Grand Challenges Canada',region:'global_majority',state:'index_only',priority:'high',access:'direct',url:'https://www.grandchallenges.ca/apply-for-funding/',note:'Innovation funding with a strong Global Majority focus. Fluxx-based application routes require dedicated call-level normalization.',focus:'Bold innovation with health and development impact.',use:'Strong fit for innovators and implementation teams; verify the live Fluxx route and eligibility criteria.'},
  {id:'global_innovation_fund',name:'Global Innovation Fund',region:'global_majority',state:'partial',priority:'high',access:'direct',url:'https://www.globalinnovation.fund/apply/about/',note:'Development innovation finance. Application-portal state and eligibility remain authoritative.',focus:'Scalable development innovation across grants, debt and equity-like instruments.',use:'Not all opportunities are conventional research grants; check the finance instrument and stage carefully.'},
  {id:'gates_foundation',name:'Gates Foundation',region:'global',state:'partial',priority:'high',access:'mixed',url:'https://www.gatesfoundation.org/about/how-we-work/grant-opportunities',note:'Public RFPs coexist with invitation-only funding. The interface never presents invitation-only programmes as open applications.',focus:'Global health, development, agriculture, education and catalytic innovation.',use:'Look for explicit RFPs or Grand Challenges routes. Do not assume a general programme page means unsolicited applications are accepted.'},
  {id:'grand_challenges',name:'Grand Challenges Network',region:'global',state:'index_only',priority:'high',access:'mixed',url:'https://grandchallenges.org/challenges/',note:'Discovery network. Final eligibility must resolve to the primary issuing partner.',focus:'Challenge-led innovation across health and development.',use:'Use the network for discovery, then verify the issuing partner’s authoritative call page.'},
  {id:'fogarty',name:'Fogarty International Center',region:'global',state:'index_only',priority:'critical',access:'direct',url:'https://www.fic.nih.gov/Funding/Pages/default.aspx',note:'NIH-linked global health research and training; final notice rules come from the NIH notice or Grants.gov.',focus:'Global health research, research training and institutional capacity.',use:'Particularly relevant to international health research partnerships; always read the linked NIH funding opportunity announcement.'},
  {id:'nih',name:'US National Institutes of Health',region:'global',state:'partial',priority:'critical',access:'mixed',url:'https://grants.nih.gov/funding',note:'Large global research funding ecosystem. Foreign-organisation eligibility is kept separate from foreign-component participation.',focus:'Biomedical, behavioural, clinical and implementation research across NIH institutes.',use:'Check whether foreign organisations may apply, whether foreign components are permitted, and whether the specific notice is active.'},
  {id:'novo_nordisk_foundation',name:'Novo Nordisk Foundation',region:'global',state:'index_only',priority:'high',access:'mixed',url:'https://novonordiskfonden.dk/en/grants/',note:'Major philanthropic science funder; tracked at the authoritative grants index pending deeper call normalization.',focus:'Biomedical science, health, sustainability and research infrastructure.',use:'Use the official grant index and confirm geographic and institutional eligibility per programme.'},
  {id:'pfizer_independent_grants',name:'Pfizer Independent Grants',region:'global',state:'partial',priority:'high',access:'mixed',url:'https://www.pfizer.com/about/programs-policies/grants',note:'Independent medical education, quality improvement and research opportunities are kept distinct.',focus:'Independent medical education, quality improvement and selected research calls.',use:'Match the opportunity type carefully; education/QI support is not equivalent to investigator research funding.'},
  {id:'gsk_supported_studies',name:'GSK Supported Studies',region:'global',state:'manual_verify',priority:'high',access:'mixed',url:'https://iss.gsk.com/',note:'Investigator-sponsored studies vary by disease area and submission window and require portal-level verification.',focus:'Investigator-sponsored and supported collaborative studies.',use:'Verify whether the relevant disease area is accepting submissions and what form of support is available.'},
  {id:'gavi',name:'Gavi, the Vaccine Alliance',region:'global_majority',state:'partial',priority:'high',access:'direct',url:'https://www.gavi.org/investing-gavi/funding',note:'Country financing, market-shaping and research/innovation opportunities are distinguished rather than pooled.',focus:'Immunisation systems, vaccine access, market shaping and selected innovation opportunities.',use:'Distinguish country financing from competitive research or innovation calls.'},
  {id:'ukri',name:'UK Research and Innovation',region:'UK',state:'structured_beta',priority:'critical',access:'mixed',url:'https://www.ukri.org/opportunity/',note:'Structured Funding Finder coverage with deterministic extraction of status, funder, award and deadline fields.',focus:'Research and innovation across UKRI councils and cross-council programmes.',use:'Strong starting point for UK-based researchers and international partnerships; use the call page for final applicant eligibility.'},
  {id:'nihr',name:'NIHR Research Funding',region:'UK',state:'structured_beta',priority:'critical',access:'mixed',url:'https://www.nihr.ac.uk/research-funding',note:'UK health and care research funding; Global Health opportunities are especially relevant to LMIC partnerships.',focus:'Applied health, social care, public health, clinical and global health research.',use:'Programme rules vary substantially; staged deadlines and contracting arrangements should be checked on the live call.'},
  {id:'wellcome',name:'Wellcome',region:'global',state:'structured_beta',priority:'critical',access:'direct',url:'https://wellcome.org/research-funding/schemes',note:'Major biomedical and health research funder with direct eligibility for many LMIC-based organisations.',focus:'Discovery research, early-career and career development, mental health, infectious disease and climate & health.',use:'Many schemes support eligible organisations in LMICs. Verify the current scheme deadline and administering-organisation rules.'},
  {id:'eu',name:'EU Funding & Tenders',region:'Europe',state:'structured_beta',priority:'critical',access:'mixed',url:'https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/topic-search',note:'Horizon Europe and related calls normalized from the European Commission public REST API rather than scraping the SPA.',focus:'Horizon Europe, missions, partnerships, EU4Health and related European programmes.',use:'Consortium and country-association rules are call-specific. Use the official topic page and documents before forming a bid team.'},
  {"id":"edctp3","name":"Global Health EDCTP3","region":"Africa","state":"index_only","priority":"critical","access":"direct","url":"https://global-health-edctp3.europa.eu/funding-opportunities_en","note":"EU–Africa partnership funding clinical research on infectious diseases, with African institutions eligible to lead and receive funds directly.","focus":"Clinical trials, infectious diseases of poverty, health systems and research capacity in sub-Saharan Africa.","use":"One of the most Africa-accessible EU instruments. Confirm the specific call's country and consortium rules on the topic page."},
  {"id":"african_academy_sciences","name":"African Academy of Sciences","region":"Africa","state":"index_only","priority":"high","access":"direct","url":"https://aasciences.africa/","note":"Continental academy hosting and signposting African-led research and fellowship programmes.","focus":"Science leadership, health, climate and research capacity across Africa.","use":"Use as a gateway to AAS-linked programmes; confirm the administering programme and current call status."},
  {"id":"aref","name":"Africa Research Excellence Fund","region":"Africa","state":"index_only","priority":"high","access":"direct","url":"https://www.aref-africa.org.uk/","note":"Early-career health research fellowships and development awards for African researchers.","focus":"Health research capacity and career development for early-career African investigators.","use":"Strong fit for early-career African researchers; check the current round and eligibility window."},
  {"id":"carta","name":"CARTA","region":"Africa","state":"index_only","priority":"medium","access":"direct","url":"https://cartafrica.org/","note":"Consortium for Advanced Research Training in Africa; doctoral and research-capacity programmes.","focus":"Public and population health doctoral training and research capacity strengthening.","use":"Primarily a training and PhD-fellowship route; verify participating institutions and intake timing."},
  {"id":"twas","name":"TWAS (The World Academy of Sciences)","region":"global_majority","state":"index_only","priority":"high","access":"direct","url":"https://twas.org/opportunities","note":"Grants and fellowships specifically for researchers based in the Global South.","focus":"Research grants, PhD and postdoctoral fellowships and exchange for developing-country scientists.","use":"Directly aimed at Global Majority researchers; match the scheme to your career stage and country."},
  {"id":"owsd","name":"OWSD","region":"global_majority","state":"index_only","priority":"medium","access":"direct","url":"https://owsd.net/","note":"Organization for Women in Science for the Developing World; fellowships and awards.","focus":"Career development and fellowships for women scientists in the Global South.","use":"Check eligibility by country income group, gender and career stage before applying."},
  {"id":"africa_cdc","name":"Africa CDC","region":"Africa","state":"index_only","priority":"medium","access":"direct","url":"https://africacdc.org/","note":"African Union public-health agency; periodic research, innovation and workforce calls.","focus":"Public health, epidemic preparedness, health workforce and continental health security.","use":"Opportunities are intermittent and programme-specific; confirm the current call and partner requirements."},
  {"id":"mq","name":"MQ Mental Health Research","region":"global","state":"index_only","priority":"high","access":"direct","url":"https://www.mqmentalhealth.org/research/","note":"Dedicated mental-health research funder supporting fellowships and project grants.","focus":"Mental health science, youth mental health, data science and lived-experience research.","use":"Relevant to global mental-health researchers; verify the current scheme and country eligibility."},
  {"id":"nimh","name":"US NIMH","region":"global","state":"index_only","priority":"high","access":"mixed","url":"https://www.nimh.nih.gov/funding","note":"US National Institute of Mental Health funding within the NIH ecosystem.","focus":"Mental-health neuroscience, clinical, services and global mental-health research.","use":"Foreign-organisation eligibility varies by notice; read the specific NIH funding opportunity announcement."},
  {"id":"find","name":"FIND","region":"global_majority","state":"index_only","priority":"high","access":"direct","url":"https://www.finddx.org/","note":"Global diagnostics alliance; calls are often published as PDFs on the tenders/opportunities pages.","focus":"Diagnostics development, evaluation and access for diseases affecting LMICs.","use":"Treat attached call PDFs as authoritative; confirm the diagnostic area and partnership model."},
  {"id":"unitaid","name":"Unitaid","region":"global_majority","state":"index_only","priority":"high","access":"direct","url":"https://unitaid.org/","note":"Global health initiative funding access to health products for LMICs via calls for proposals.","focus":"Market access and scale-up for medicines, diagnostics and prevention in LMICs.","use":"Opportunities are proposal-driven and time-bound; check the current calls page for scope."},
  {"id":"mmv","name":"Medicines for Malaria Venture","region":"global_majority","state":"index_only","priority":"medium","access":"direct","url":"https://www.mmv.org/","note":"Product-development partnership funding antimalarial R&D and access.","focus":"Malaria drug discovery, development and access research.","use":"Engagement is usually partnership- and portfolio-based; confirm current calls or expressions of interest."},
  {"id":"dndi","name":"DNDi","region":"global_majority","state":"index_only","priority":"medium","access":"direct","url":"https://dndi.org/","note":"Drugs for Neglected Diseases initiative; R&D partnerships for neglected populations.","focus":"Treatments for neglected tropical diseases and other diseases of poverty.","use":"Primarily collaborative R&D; verify whether an open call or partnership route applies."},
  {"id":"path","name":"PATH","region":"global_majority","state":"index_only","priority":"medium","access":"mixed","url":"https://www.path.org/","note":"Global health nonprofit; periodic partnership and innovation opportunities.","focus":"Health technologies, systems and implementation in LMICs.","use":"Opportunities are programme-specific; confirm the current call and partner eligibility."},
  {"id":"alzheimers_research_uk","name":"Alzheimer's Research UK","region":"UK","state":"index_only","priority":"medium","access":"mixed","url":"https://www.alzheimersresearchuk.org/for-researchers/","note":"UK dementia research charity funding grants and fellowships.","focus":"Dementia and neurodegeneration research across discovery to translation.","use":"Check scheme-specific eligibility, including career stage and host-institution rules."},
  {"id":"erc","name":"European Research Council","region":"Europe","state":"index_only","priority":"critical","access":"mixed","url":"https://erc.europa.eu/apply-grant","note":"Frontier-research grants (Starting, Consolidator, Advanced, Synergy) for excellent investigators.","focus":"Investigator-led frontier research across all disciplines.","use":"The host institution must be in the EU or an associated country; check residency and portability rules."},
  {"id":"msca","name":"Marie Sklodowska-Curie Actions","region":"Europe","state":"index_only","priority":"high","access":"mixed","url":"https://marie-sklodowska-curie-actions.ec.europa.eu/","note":"Fellowships, doctoral networks and staff exchanges, including global mobility routes.","focus":"Researcher mobility, training and career development, including some non-EU routes.","use":"Some actions support incoming/outgoing global mobility; match the action type to your stage."},
  {"id":"eic","name":"European Innovation Council","region":"Europe","state":"index_only","priority":"high","access":"mixed","url":"https://eic.ec.europa.eu/eic-funding-opportunities_en","note":"Deep-tech and breakthrough-innovation funding, grants and blended finance.","focus":"Deep tech, startup and scale-up innovation with translational potential.","use":"Eligibility is EU/associated-country centric; confirm entity type and instrument before applying."},
  {"id":"ihi","name":"Innovative Health Initiative","region":"Europe","state":"index_only","priority":"high","access":"mixed","url":"https://www.ihi.europa.eu/apply-funding","note":"EU public-private partnership funding cross-sector health research consortia.","focus":"Health research and innovation across industry-academia consortia.","use":"Consortium composition rules are strict; read the topic text before forming a team."},
  {"id":"eit_health","name":"EIT Health","region":"Europe","state":"index_only","priority":"medium","access":"mixed","url":"https://eithealth.eu/","note":"European health-innovation network offering programmes and challenge calls.","focus":"Health innovation, entrepreneurship and education across Europe.","use":"Offerings mix funding, acceleration and training; confirm the specific programme's terms."},
  {"id":"mrc","name":"Medical Research Council","region":"UK","state":"index_only","priority":"critical","access":"mixed","url":"https://www.ukri.org/councils/mrc/","note":"UKRI biomedical council; individual calls appear in the UKRI Funding Finder.","focus":"Biomedical and health research from discovery to translation, including global health.","use":"Applicant eligibility is set per call on the UKRI opportunity page; check international-partner rules."},
  {"id":"innovate_uk","name":"Innovate UK","region":"UK","state":"index_only","priority":"high","access":"mixed","url":"https://www.ukri.org/councils/innovate-uk/","note":"UK innovation agency; competitions run through the Innovation Funding Service.","focus":"Business-led innovation, including health, deep tech and net zero.","use":"Most competitions require a UK-registered organisation; check match-funding and entity rules."},
  {"id":"ams","name":"Academy of Medical Sciences","region":"UK","state":"index_only","priority":"high","access":"mixed","url":"https://acmedsci.ac.uk/grants-and-schemes","note":"Career-development and networking schemes, several with global-health relevance.","focus":"Biomedical career development, mentoring and international collaboration.","use":"Schemes are career-stage specific; some support international/LMIC partnerships."},
  {"id":"cruk","name":"Cancer Research UK","region":"UK","state":"index_only","priority":"high","access":"mixed","url":"https://www.cancerresearchuk.org/funding-for-researchers","note":"Major cancer research charity funding discovery, clinical and prevention research.","focus":"Cancer discovery, clinical trials, prevention and early detection.","use":"Check scheme-specific host-institution and eligibility rules before applying."},
  {"id":"bhf","name":"British Heart Foundation","region":"UK","state":"index_only","priority":"medium","access":"mixed","url":"https://www.bhf.org.uk/for-professionals/information-for-researchers","note":"Cardiovascular research charity funding grants and fellowships.","focus":"Cardiovascular and circulatory disease research.","use":"Eligibility is scheme-specific; verify host-institution and career-stage requirements."},
  {"id":"wellcome_leap","name":"Wellcome Leap","region":"global","state":"index_only","priority":"high","access":"mixed","url":"https://wellcomeleap.org/","note":"Mission-driven programmes funding ambitious, time-bound health research (distinct from Wellcome grants).","focus":"Bold, milestone-based health and life-science programmes.","use":"Participation is programme- and milestone-based; confirm the active programme's terms."},
  {"id":"czi","name":"Chan Zuckerberg Initiative","region":"global","state":"index_only","priority":"high","access":"mixed","url":"https://chanzuckerberg.com/grants-ventures/","note":"Philanthropic funder of science, including tools, open science and global health.","focus":"Biomedical science, open tools, and science capacity, with some global reach.","use":"RFAs are periodic; confirm geographic eligibility for the specific opportunity."},
  {"id":"open_philanthropy","name":"Open Philanthropy","region":"global","state":"index_only","priority":"medium","access":"mixed","url":"https://www.openphilanthropy.org/request-for-proposals/","note":"Philanthropic funder publishing requests for proposals across cause areas.","focus":"Global health, scientific research and high-impact cause areas.","use":"Coverage is RFP-driven; read the specific RFP scope and eligibility."},
  {"id":"rockefeller","name":"Rockefeller Foundation","region":"global","state":"index_only","priority":"medium","access":"mixed","url":"https://www.rockefellerfoundation.org/","note":"Global foundation funding health, food, climate and development initiatives.","focus":"Health, food systems, climate and inclusive development.","use":"Most support is initiative- or partnership-based; confirm current opportunities and eligibility."},
  {"id":"mastercard_foundation","name":"Mastercard Foundation","region":"Africa","state":"index_only","priority":"high","access":"direct","url":"https://mastercardfdn.org/","note":"Large Africa-focused foundation funding education, youth employment and health programmes.","focus":"Youth, education, employment and health with a strong Africa focus.","use":"Programmes are partnership-based; confirm the current initiative and institutional eligibility."}
];

const els={cards:document.getElementById('cards'),resultCount:document.getElementById('resultCount'),sourceCount:document.getElementById('sourceCount'),structuredCount:document.getElementById('structuredCount'),region:document.getElementById('regionFilter'),state:document.getElementById('stateFilter'),priority:document.getElementById('priorityFilter'),search:document.getElementById('searchInput'),reset:document.getElementById('resetFilters'),theme:document.getElementById('themeToggle'),dialog:document.getElementById('resourceDialog'),dialogContent:document.getElementById('dialogContent')};

function escapeHTML(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function labelRegion(region){return({global_majority:'Global Majority',global:'Global',UK:'United Kingdom',Europe:'Europe',Africa:'Africa'})[region]||region;}
function scrollDiscover(){document.getElementById('discover')?.scrollIntoView({behavior:'smooth',block:'start'});}
function render(){const q=els.search.value.trim().toLowerCase();const filtered=sources.filter(s=>(els.region.value==='all'||s.region===els.region.value)&&(els.state.value==='all'||s.state===els.state.value)&&(els.priority.value==='all'||s.priority===els.priority.value)&&(!q||`${s.name} ${s.note} ${s.focus} ${s.use} ${s.region} ${s.state} ${s.access}`.toLowerCase().includes(q)));els.resultCount.textContent=filtered.length;els.cards.innerHTML=filtered.length?filtered.map(s=>`<article class="funding-card"><div class="card-top"><span class="badge ${escapeHTML(s.state)}">${escapeHTML(s.state)}</span><span class="priority">${escapeHTML(s.priority)}</span></div><h3>${escapeHTML(s.name)}</h3><div class="meta">${escapeHTML(labelRegion(s.region))} • Global Majority access: ${escapeHTML(s.access)}</div><p>${escapeHTML(s.note)}</p><div class="card-bottom"><span class="meta">Eligibility: verify at source</span><div class="card-actions"><button class="details-button" type="button" data-details="${escapeHTML(s.id)}">Details</button><a class="source-link" href="${escapeHTML(s.url)}" target="_blank" rel="noreferrer">Primary source ↗</a></div></div></article>`).join(''):`<div class="funding-card"><h3>No matching sources</h3><p>Try broadening a filter. Unknown coverage is not treated as ineligibility.</p></div>`;bindDetails();}
function bindDetails(){document.querySelectorAll('[data-details]').forEach(btn=>btn.addEventListener('click',()=>openDetails(btn.dataset.details)));}
function openDetails(id){const s=sources.find(x=>x.id===id);if(!s||!els.dialog)return;els.dialogContent.innerHTML=`<p class="eyebrow">FUNDER RESOURCE</p><h2 id="dialogTitle">${escapeHTML(s.name)}</h2><div class="dialog-meta"><span class="badge ${escapeHTML(s.state)}">${escapeHTML(s.state)}</span><span class="priority">${escapeHTML(s.priority)}</span><span class="priority">${escapeHTML(labelRegion(s.region))}</span></div><p><strong>What it funds:</strong> ${escapeHTML(s.focus)}</p><p><strong>How to use this resource:</strong> ${escapeHTML(s.use)}</p><p><strong>Current evidence note:</strong> ${escapeHTML(s.note)}</p><p><strong>Eligibility:</strong> not determined by this site. Verify the live call at the primary source.</p><div class="dialog-actions"><a class="button primary" href="${escapeHTML(s.url)}" target="_blank" rel="noreferrer">Open primary source ↗</a><button class="button" type="button" data-dialog-filter="${escapeHTML(s.region)}">Show similar sources</button></div>`;els.dialog.showModal();els.dialogContent.querySelector('[data-dialog-filter]')?.addEventListener('click',e=>{els.dialog.close();els.region.value=e.currentTarget.dataset.dialogFilter;render();scrollDiscover();});}
function resetFilters(){els.region.value='all';els.state.value='all';els.priority.value='all';els.search.value='';render();}
function setTheme(theme,persist=true){document.documentElement.dataset.theme=theme;const dark=theme==='dark';els.theme?.setAttribute('aria-pressed',String(dark));const label=els.theme?.querySelector('.theme-label');if(label)label.textContent=dark?'Light':'Dark';if(persist)localStorage.setItem('gfi-theme',theme);}
function initTheme(){const saved=localStorage.getItem('gfi-theme');const preferred=window.matchMedia?.('(prefers-color-scheme: dark)').matches?'dark':'light';setTheme(saved||preferred,false);}

els.sourceCount.textContent=sources.length;els.structuredCount.textContent=sources.filter(s=>s.state.startsWith('structured_beta')).length;[els.region,els.state,els.priority].forEach(el=>el.addEventListener('change',render));els.search.addEventListener('input',render);els.reset.addEventListener('click',resetFilters);els.theme?.addEventListener('click',()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));
document.querySelectorAll('[data-filter-region]').forEach(el=>el.addEventListener('click',e=>{els.region.value=e.currentTarget.dataset.filterRegion;els.search.value='';render();}));document.querySelectorAll('[data-search]').forEach(el=>el.addEventListener('click',e=>{els.search.value=e.currentTarget.dataset.search;render();scrollDiscover();}));
els.dialog?.addEventListener('click',e=>{if(e.target===els.dialog)els.dialog.close();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&els.dialog?.open)els.dialog.close();});
initTheme();render();
// In-page navigation is handled in JS so it works inside embeds/iframes (e.g. Wix),
// where native "#anchor" hash scrolling can be unreliable. Progressive: if JS is
// disabled the plain anchors still work on the standalone site.
document.addEventListener('click',function(e){var a=e.target.closest&&e.target.closest('a[href^="#"]');if(!a)return;var id=a.getAttribute('href').slice(1);if(!id)return;var el=document.getElementById(id);if(el){e.preventDefault();el.scrollIntoView({behavior:'smooth',block:'start'});}});
