const sources = [
  {id:'science_for_africa',name:'Science for Africa Foundation',region:'Africa',state:'structured_beta_detail',priority:'critical',access:'direct',url:'https://scienceforafrica.foundation/funding',note:'African-led funding and Grand Challenges Africa. Detail pages are structured beta; index state alone is not treated as proof a call is open.',focus:'Africa-led science, health, climate, innovation and capacity strengthening.',use:'Best for African institutions, African-led teams and partners seeking continent-focused calls. Always confirm the specific country route and stage.'},
  {id:'idrc',name:'International Development Research Centre',region:'global_majority',state:'structured_beta',priority:'high',access:'direct',url:'https://idrc-crdi.ca/en/funding',note:'Research funding focused on development priorities, with source-specific parsing for call fields and explicit budget ambiguity handling.',focus:'Development research, policy, innovation and equitable partnerships.',use:'Useful for Global Majority research teams and consortia. Award amounts are shown only when the source text is semantically unambiguous.'},
  {id:'tdr_who',name:'WHO/TDR',region:'global_majority',state:'index_only',priority:'critical',access:'direct',url:'https://tdr.who.int/grants',note:'Global health research and training. Open calls route through the eTDR portal and are therefore link-only until a structured portal adapter is available.',focus:'Diseases of poverty, implementation research, training and institutional capacity.',use:'Use this as a verified gateway to TDR opportunities; open-call status must be confirmed in eTDR.'},
  {id:'cepi',name:'CEPI',region:'global',state:'partial',priority:'high',access:'mixed',url:'https://cepi.net/calls-for-proposals',note:'Vaccine and epidemic-preparedness funding. Call index is authoritative; some specifications are PDF-backed and remain gated.',focus:'Vaccines, epidemic preparedness, platform technologies and outbreak readiness.',use:'Check the primary call and attached specifications carefully; important requirements may sit in authoritative PDFs.'},
  {id:'elrha',name:'Elrha',region:'global',state:'index_only',priority:'high',access:'direct',url:'https://www.elrha.org/funding-opportunities/',note:'Humanitarian research and innovation. Current listings can include procurement/consultancy notices, so call type must be verified.',focus:'Humanitarian health, innovation and evidence in crisis settings.',use:'Confirm whether a listing is a research grant, innovation call, procurement notice or consultancy before investing effort.'},
  {id:'grand_challenges_canada',name:'Grand Challenges Canada',region:'global_majority',state:'index_only',priority:'high',access:'direct',url:'https://www.grandchallenges.ca/apply-for-funding/',note:'Innovation funding with a strong Global Majority focus. Fluxx-based application routes require dedicated call-level normalization.',focus:'Bold innovation with health and development impact.',use:'Strong fit for innovators and implementation teams; verify the live Fluxx route and eligibility criteria.'},
  {id:'global_innovation_fund',name:'Global Innovation Fund',region:'global_majority',state:'partial',priority:'high',access:'direct',url:'https://www.globalinnovation.fund/apply/about/',note:'Development innovation finance. Application-portal state and eligibility remain authoritative.',focus:'Scalable development innovation across grants, debt and equity-like instruments.',use:'Not all opportunities are conventional research grants; check the finance instrument and stage carefully.'},
  {id:'gates_foundation',name:'Gates Foundation',region:'global',state:'partial',priority:'high',access:'mixed',url:'https://www.gatesfoundation.org/about/how-we-work/grant-opportunities',note:'Public RFPs coexist with invitation-only funding. The interface never presents invitation-only programmes as open applications.',focus:'Global health, development, agriculture, education and catalytic innovation.',use:'Look for explicit RFPs or Grand Challenges routes. Do not assume a general programme page means unsolicited applications are accepted.'},
  {id:'grand_challenges',name:'Grand Challenges Network',region:'global',state:'index_only',priority:'high',access:'mixed',url:'https://grandchallenges.org/challenges/',note:'Discovery network. Final eligibility must resolve to the primary issuing partner.',focus:'Challenge-led innovation across health and development.',use:'Use the network for discovery, then verify the issuing partner’s authoritative call page.'},
  {id:'fogarty',name:'Fogarty International Center',region:'global',state:'index_only',priority:'critical',access:'direct',url:'https://www.fic.nih.gov/Funding/Pages/default.aspx',note:'NIH-linked global health research and training; final notice rules come from the NIH notice or Grants.gov.',focus:'Global health research, research training and institutional capacity.',use:'Particularly relevant to international health research partnerships; always read the linked NIH funding opportunity announcement.'},
  {id:'nih',name:'US National Institutes of Health',region:'global',state:'partial',priority:'critical',access:'mixed',url:'https://grants.nih.gov/funding',note:'Large global research funding ecosystem. Foreign-organisation eligibility is kept separate from foreign-component participation.',focus:'Biomedical, behavioural, clinical and implementation research across NIH institutes.',use:'Check whether foreign organisations may apply, whether foreign components are permitted, and whether the specific notice is active.'},
  {id:'novo_nordisk_foundation',name:'Novo Nordisk Foundation',region:'global',state:'index_only',priority:'high',access:'mixed',url:'https://novonordiskfonden.dk/en/grants/',note:'Major philanthropic science funder; tracked at the authoritative grants index pending deeper call normalization.',focus:'Biomedical science, health, sustainability and research infrastructure.',use:'Use the official grant index and confirm geographic and institutional eligibility per programme.'},
  {id:'pfizer_independent_grants',name:'Pfizer Independent Grants',region:'global',state:'partial',priority:'high',access:'mixed',url:'https://www.pfizer.com/about/programs-policies/grants',note:'Independent medical education, quality improvement and research opportunities are kept distinct.',focus:'Independent medical education, quality improvement and selected research calls.',use:'Match the opportunity type carefully; education/QI support is not equivalent to investigator research funding.'},
  {id:'gsk_supported_studies',name:'GSK Supported Studies',region:'global',state:'manual_verify',priority:'high',access:'mixed',url:'https://iss.gsk.com/',note:'Investigator-sponsored studies vary by disease area and submission window and require portal-level verification.',focus:'Investigator-sponsored and supported collaborative studies.',use:'Verify whether the relevant disease area is accepting submissions and what form of support is available.'},
  {id:'gavi',name:'Gavi, the Vaccine Alliance',region:'global_majority',state:'partial',priority:'high',access:'direct',url:'https://www.gavi.org/investing-gavi/funding',note:'Country financing, market-shaping and research/innovation opportunities are distinguished rather than pooled.',focus:'Immunisation systems, vaccine access, market shaping and selected innovation opportunities.',use:'Distinguish country financing from competitive research or innovation calls.'},
  {id:'ukri',name:'UK Research and Innovation',region:'UK',state:'structured_beta',priority:'critical',access:'mixed',url:'https://www.ukri.org/opportunity/',note:'Structured Funding Finder coverage with deterministic extraction of status, funder, award and deadline fields.',focus:'Research and innovation across UKRI councils and cross-council programmes.',use:'Strong starting point for UK-based researchers and international partnerships; use the call page for final applicant eligibility.'},
  {id:'nihr',name:'NIHR Research Funding',region:'UK',state:'structured_beta',priority:'critical',access:'mixed',url:'https://www.nihr.ac.uk/research-funding',note:'UK health and care research funding; Global Health opportunities are especially relevant to LMIC partnerships.',focus:'Applied health, social care, public health, clinical and global health research.',use:'Programme rules vary substantially; staged deadlines and contracting arrangements should be checked on the live call.'},
  {id:'wellcome',name:'Wellcome',region:'global',state:'structured_beta',priority:'critical',access:'direct',url:'https://wellcome.org/research-funding/schemes',note:'Major biomedical and health research funder with direct eligibility for many LMIC-based organisations.',focus:'Discovery research, early-career and career development, mental health, infectious disease and climate & health.',use:'Many schemes support eligible organisations in LMICs. Verify the current scheme deadline and administering-organisation rules.'},
  {id:'eu',name:'EU Funding & Tenders',region:'Europe',state:'structured_beta',priority:'critical',access:'mixed',url:'https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/topic-search',note:'Horizon Europe and related calls normalized from the European Commission public REST API rather than scraping the SPA.',focus:'Horizon Europe, missions, partnerships, EU4Health and related European programmes.',use:'Consortium and country-association rules are call-specific. Use the official topic page and documents before forming a bid team.'}
];

const els={cards:document.getElementById('cards'),resultCount:document.getElementById('resultCount'),sourceCount:document.getElementById('sourceCount'),structuredCount:document.getElementById('structuredCount'),region:document.getElementById('regionFilter'),state:document.getElementById('stateFilter'),priority:document.getElementById('priorityFilter'),search:document.getElementById('searchInput'),reset:document.getElementById('resetFilters'),theme:document.getElementById('themeToggle'),dialog:document.getElementById('resourceDialog'),dialogContent:document.getElementById('dialogContent')};

function escapeHTML(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function labelRegion(region){return({global_majority:'Global Majority',global:'Global',UK:'United Kingdom',Europe:'Europe',Africa:'Africa'})[region]||region;}
function scrollDiscover(){document.getElementById('discover')?.scrollIntoView({behavior:'smooth',block:'start'});}
function render(){const q=els.search.value.trim().toLowerCase();const filtered=sources.filter(s=>(els.region.value==='all'||s.region===els.region.value)&&(els.state.value==='all'||s.state===els.state.value)&&(els.priority.value==='all'||s.priority===els.priority.value)&&(!q||`${s.name} ${s.note} ${s.focus} ${s.use} ${s.region} ${s.state} ${s.access}`.toLowerCase().includes(q)));els.resultCount.textContent=filtered.length;els.cards.innerHTML=filtered.length?filtered.map(s=>`<article class="funding-card"><div class="card-top"><span class="badge ${escapeHTML(s.state)}">${escapeHTML(s.state)}</span><span class="priority">${escapeHTML(s.priority)}</span></div><h3>${escapeHTML(s.name)}</h3><div class="meta">${escapeHTML(labelRegion(s.region))} • Global Majority access: ${escapeHTML(s.access)}</div><p>${escapeHTML(s.note)}</p><div class="card-bottom"><span class="meta">Eligibility: verify at source</span><div class="card-actions"><button class="details-button" type="button" data-details="${escapeHTML(s.id)}">Details</button><a class="source-link" href="${escapeHTML(s.url)}" target="_blank" rel="noreferrer">Primary source ↗</a></div></div></article>`).join(''):`<div class="funding-card"><h3>No matching sources</h3><p>Try broadening a filter. Unknown coverage is not treated as ineligibility.</p></div>`;bindDetails();}
function bindDetails(){document.querySelectorAll('[data-details]').forEach(btn=>btn.addEventListener('click',()=>openDetails(btn.dataset.details)));}
function openDetails(id){const s=sources.find(x=>x.id===id);if(!s||!els.dialog)return;els.dialogContent.innerHTML=`<p class="eyebrow">FUNDER RESOURCE</p><h2 id="dialogTitle">${escapeHTML(s.name)}</h2><div class="dialog-meta"><span class="badge ${escapeHTML(s.state)}">${escapeHTML(s.state)}</span><span class="priority">${escapeHTML(s.priority)}</span><span class="priority">${escapeHTML(labelRegion(s.region))}</span></div><p><strong>What it funds:</strong> ${escapeHTML(s.focus)}</p><p><strong>How to use this resource:</strong> ${escapeHTML(s.use)}</p><p><strong>Current evidence note:</strong> ${escapeHTML(s.note)}</p><p><strong>Eligibility:</strong> not determined by this site. Verify the live call at the primary source.</p><div class="dialog-actions"><a class="button primary" href="${escapeHTML(s.url)}" target="_blank" rel="noreferrer">Open primary source ↗</a><button class="button" type="button" data-dialog-filter="${escapeHTML(s.region)}">Show similar sources</button></div>`;els.dialog.showModal();els.dialogContent.querySelector('[data-dialog-filter]')?.addEventListener('click',e=>{els.dialog.close();els.region.value=e.currentTarget.dataset.dialogFilter;render();scrollDiscover();});}
function resetFilters(){els.region.value='all';els.state.value='all';els.priority.value='all';els.search.value='';render();}
function setTheme(theme,persist=true){document.documentElement.dataset.theme=theme;const dark=theme==='dark';els.theme?.setAttribute('aria-pressed',String(dark));const label=els.theme?.querySelector('.theme-label');if(label)label.textContent=dark?'Light':'Dark';if(persist)localStorage.setItem('gfi-theme',theme);}
function initTheme(){const saved=localStorage.getItem('gfi-theme');const preferred=window.matchMedia?.('(prefers-color-scheme: dark)').matches?'dark':'light';setTheme(saved||preferred,false);}

els.sourceCount.textContent=sources.length;els.structuredCount.textContent=sources.filter(s=>s.state.startsWith('structured_beta')).length;[els.region,els.state,els.priority].forEach(el=>el.addEventListener('change',render));els.search.addEventListener('input',render);els.reset.addEventListener('click',resetFilters);els.theme?.addEventListener('click',()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));
document.querySelectorAll('[data-filter-region]').forEach(el=>el.addEventListener('click',e=>{els.region.value=e.currentTarget.dataset.filterRegion;els.search.value='';render();}));document.querySelectorAll('[data-search]').forEach(el=>el.addEventListener('click',e=>{els.search.value=e.currentTarget.dataset.search;render();scrollDiscover();}));
els.dialog?.addEventListener('click',e=>{if(e.target===els.dialog)els.dialog.close();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&els.dialog?.open)els.dialog.close();});
initTheme();render();